<?php

declare(strict_types=1);

namespace App\Api\LogEntry;

final readonly class LogEntryView
{
    public function __construct(
        public int $id,
        public string $qsoDate,
        public string $timeOn,
        public ?string $timeOff,
        public string $callsign,
        public float $frequency,
        public string $mode,
        public ?string $rstSent,
        public ?string $rstReceived,
        public ?string $name,
        public ?string $qth,
        public ?string $grid,
        public ?string $state,
        public ?string $county,
        public ?string $award,
        public ?int $adif,
        public ?string $band,
        public ?string $dxccRef,
        public ?string $remarks,
        public ?string $qslSent,
        public ?string $qslReceived,
        public ?string $qslVia,
        public ?string $iota,
        public ?string $power,
        public ?int $itu,
        public ?int $waz,
        public ?string $idCall,
        public ?string $lotwSentDate,
        public ?string $lotwReceivedDate,
        public ?string $lotwSent,
        public ?string $lotwReceived,
        public ?string $continent,
        public ?string $qslSentDate,
        public ?string $qslReceivedDate,
        public ?string $clubNumber1,
        public ?string $clubNumber2,
        public ?string $clubNumber3,
        public ?string $clubNumber4,
        public ?string $clubNumber5,
        public ?string $eqslSent,
        public ?string $eqslSentDate,
        public ?string $eqslReceived,
        public ?string $eqslReceivedDate,
        public ?float $receiveFrequency,
        public ?string $satellite,
        public ?string $propagationMode,
        public ?string $stx,
        public ?string $srx,
        public ?string $stxString,
        public ?string $srxString,
        public ?string $contestName,
        public ?string $dok,
        public ?string $operator,
        public ?string $myLocator,
        public ?int $qsoDxcc,
        public ?int $profileId,
    ) {
    }

    /**
     * @return array<string, int|float|string|null>
     */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'qsoDate' => $this->qsoDate,
            'timeOn' => $this->timeOn,
            'timeOff' => $this->timeOff,
            'callsign' => $this->callsign,
            'frequency' => $this->frequency,
            'mode' => $this->mode,
            'rstSent' => $this->rstSent,
            'rstReceived' => $this->rstReceived,
            'name' => $this->name,
            'qth' => $this->qth,
            'grid' => $this->grid,
            'state' => $this->state,
            'county' => $this->county,
            'award' => $this->award,
            'adif' => $this->adif,
            'band' => $this->band,
            'dxccRef' => $this->dxccRef,
            'remarks' => $this->remarks,
            'qslSent' => $this->qslSent,
            'qslReceived' => $this->qslReceived,
            'qslVia' => $this->qslVia,
            'iota' => $this->iota,
            'power' => $this->power,
            'itu' => $this->itu,
            'waz' => $this->waz,
            'idCall' => $this->idCall,
            'lotwSentDate' => $this->lotwSentDate,
            'lotwReceivedDate' => $this->lotwReceivedDate,
            'lotwSent' => $this->lotwSent,
            'lotwReceived' => $this->lotwReceived,
            'continent' => $this->continent,
            'qslSentDate' => $this->qslSentDate,
            'qslReceivedDate' => $this->qslReceivedDate,
            'clubNumber1' => $this->clubNumber1,
            'clubNumber2' => $this->clubNumber2,
            'clubNumber3' => $this->clubNumber3,
            'clubNumber4' => $this->clubNumber4,
            'clubNumber5' => $this->clubNumber5,
            'eqslSent' => $this->eqslSent,
            'eqslSentDate' => $this->eqslSentDate,
            'eqslReceived' => $this->eqslReceived,
            'eqslReceivedDate' => $this->eqslReceivedDate,
            'receiveFrequency' => $this->receiveFrequency,
            'satellite' => $this->satellite,
            'propagationMode' => $this->propagationMode,
            'stx' => $this->stx,
            'srx' => $this->srx,
            'stxString' => $this->stxString,
            'srxString' => $this->srxString,
            'contestName' => $this->contestName,
            'dok' => $this->dok,
            'operator' => $this->operator,
            'myLocator' => $this->myLocator,
            'qsoDxcc' => $this->qsoDxcc,
            'profileId' => $this->profileId,
        ];
    }
}
